dist: xenial
language: cpp
sudo: required

compiler:
  - clang
#  - gcc

#services:
#  - docker
#  - postgresql

install:
  - sudo apt update
  - sudo apt install libpq-dev postgresql-server-dev-all

script:
  - >
    cmake
    -DCMAKE_BUILD_TYPE=Release
    -DPOSTGRES_CXX_BUILD_TESTS=ON
    -B./build/${CXX}/release
    -H.
  - cmake --build build/ -- -j8
