dist: xenial
language: minimal
sudo: required

services:
  - docker

install:
  - ./docker/prepare.sh
  - docker-compose up -d postgres

script:
  - docker-compose up --build test
  - docker-compose down
