dist: xenial
language: minimal
sudo: required

env:
  - COMPILER=c++
  - COMPILER=clang++

services:
  - docker

install:
  - ./docker/prepare.sh
  - docker build -t anatoliifrolov/pgcxxtest .
  - docker-compose up -d postgres

script:
  - docker-compose run -e CXX=${COMPILER} test --run
