dist: xenial
language: minimal
sudo: required

env:
  - CC=cc    CXX=c++
  - CC=clang CXX=clang++

services:
  - docker

install:
  - ./docker/prepare.sh
  - docker build -t anatoliifrolov/pgcxxtest .
  - docker-compose up -d postgres

script:
  - docker-compose run -e CC=${CC} -e CXX=${CXX} test --run
